import {
  Body,
  Controller,
  Get,
  Headers,
  Param,
  ParseUUIDPipe,
  Patch,
  Post,
  UseGuards,
} from '@nestjs/common';
import {
  ApiBearerAuth,
  ApiHeader,
  ApiOperation,
  ApiParam,
  ApiResponse,
  ApiTags,
} from '@nestjs/swagger';
import { UserRole } from '@prisma/client';

import type { JwtPayload } from '../../auth/types/jwt-payload.type';
import { CurrentUser } from '../../common/decorators/current-user.decorator';
import { Roles } from '../../common/decorators/roles.decorator';
import { JwtAuthGuard } from '../../common/guards/jwt-auth.guard';
import { RolesGuard } from '../../common/guards/roles.guard';
import {
  BulkUpdateRecurringPlanSessionsDTO,
  CancelRecurringCoachingPlanDTO,
  CreateRecurringCoachingPlanDTO,
  CreateStaffRecurringCashEnrollmentDTO,
  EnrollRecurringCoachingPlanDTO,
  InitiateRecurringBillingCyclePaymentDTO,
  PreviewRecurringCoachingPlanDTO,
  RecurringCoachingPlanPreviewResponseDTO,
  RecurringBillingCycleCheckoutResponseDTO,
  UpdateRecurringPlanSessionDTO,
} from './dto/recurring-coaching-plan.dto';
import { RecurringCoachingPlanService } from './recurring-coaching-plan.service';

@ApiTags('Recurring Coaching Plans')
@ApiBearerAuth('access-token')
@UseGuards(JwtAuthGuard)
@Controller('bookings/recurring-coaching-plans')
export class RecurringCoachingPlanController {
  constructor(
    private readonly recurringPlanService: RecurringCoachingPlanService,
  ) {}

  @Post('enroll')
  @UseGuards(RolesGuard)
  @Roles(UserRole.member)
  @ApiOperation({
    summary:
      'Start full PayMongo checkout for a monthly coaching offer without creating a product-visible enrollment.',
  })
  @ApiHeader({
    name: 'Idempotency-Key',
    required: true,
    description: 'UUID v4 generated by the client and reused on retries.',
  })
  @ApiResponse({
    status: 201,
    description: 'Recurring coaching enrollment created.',
  })
  enroll(
    @CurrentUser() user: JwtPayload,
    @Body() dto: EnrollRecurringCoachingPlanDTO,
    @Headers('idempotency-key') idempotencyKey: string | undefined,
  ) {
    return this.recurringPlanService.enroll(user, dto, idempotencyKey);
  }

  @Post('cash')
  @UseGuards(RolesGuard)
  @Roles(UserRole.admin, UserRole.staff)
  @ApiHeader({
    name: 'Idempotency-Key',
    required: true,
    description: 'UUID v4 generated by the staff client and reused on retries.',
  })
  @ApiOperation({
    summary:
      'Atomically register a fully paid monthly coaching enrollment by cash.',
  })
  createStaffCashEnrollment(
    @CurrentUser() user: JwtPayload,
    @Body() dto: CreateStaffRecurringCashEnrollmentDTO,
    @Headers('idempotency-key') idempotencyKey: string | undefined,
  ) {
    return this.recurringPlanService.createStaffCashEnrollment(
      user,
      dto,
      idempotencyKey,
    );
  }

  @Post('preview')
  @UseGuards(RolesGuard)
  @Roles(UserRole.admin, UserRole.coach)
  @ApiOperation({
    summary:
      'Preview generated recurring coaching sessions and conflicts without persisting rows.',
  })
  @ApiResponse({
    status: 201,
    description: 'Recurring plan preview returned.',
    type: RecurringCoachingPlanPreviewResponseDTO,
  })
  previewPlan(
    @CurrentUser() user: JwtPayload,
    @Body() dto: PreviewRecurringCoachingPlanDTO,
  ) {
    return this.recurringPlanService.previewPlan(user, dto);
  }

  @Post()
  @UseGuards(RolesGuard)
  @Roles(UserRole.admin, UserRole.coach)
  @ApiOperation({
    summary:
      'Create a coach-authored recurring schedule. Appointments are created only after the member completes full PayMongo payment.',
  })
  @ApiResponse({ status: 201, description: 'Recurring coaching plan created.' })
  createPlan(
    @CurrentUser() user: JwtPayload,
    @Body() dto: CreateRecurringCoachingPlanDTO,
  ) {
    return this.recurringPlanService.createPlan(user, dto);
  }

  @Get()
  @ApiOperation({
    summary: 'List recurring coaching plans visible to the authenticated role.',
  })
  listPlans(@CurrentUser() user: JwtPayload) {
    return this.recurringPlanService.listPlans(user);
  }

  @Get(':id/sessions')
  @ApiOperation({ summary: 'List sessions for a recurring coaching plan.' })
  @ApiParam({ name: 'id', format: 'uuid' })
  getPlanSessions(
    @CurrentUser() user: JwtPayload,
    @Param('id', ParseUUIDPipe) id: string,
  ) {
    return this.recurringPlanService.getPlanSessions(user, id);
  }

  @Post(':id/billing-cycles/:cycleId/pay')
  @UseGuards(RolesGuard)
  @Roles(UserRole.member, UserRole.admin, UserRole.staff)
  @ApiOperation({
    summary:
      'Start the full PayMongo checkout for a recurring coaching monthly billing cycle.',
  })
  @ApiParam({ name: 'id', format: 'uuid' })
  @ApiParam({ name: 'cycleId', format: 'uuid' })
  @ApiResponse({
    status: 201,
    description: 'Recurring coaching billing cycle payment initialized.',
    type: RecurringBillingCycleCheckoutResponseDTO,
  })
  @ApiResponse({
    status: 410,
    description:
      'Product-visible recurring billing-cycle payment is retired; use initial full-payment enrollment or atomic staff cash enrollment.',
  })
  initiateBillingCyclePayment(
    @CurrentUser() user: JwtPayload,
    @Param('id', ParseUUIDPipe) id: string,
    @Param('cycleId', ParseUUIDPipe) cycleId: string,
    @Body() dto: InitiateRecurringBillingCyclePaymentDTO,
  ) {
    return this.recurringPlanService.initiateBillingCyclePayment(
      user,
      id,
      cycleId,
      dto,
    );
  }

  @Patch(':id/sessions/bulk')
  @UseGuards(RolesGuard)
  @Roles(UserRole.admin, UserRole.coach)
  @ApiOperation({
    summary:
      'Update future non-completed sessions from a selected recurring session forward.',
  })
  @ApiParam({ name: 'id', format: 'uuid' })
  bulkUpdateFutureSessions(
    @CurrentUser() user: JwtPayload,
    @Param('id', ParseUUIDPipe) id: string,
    @Body() dto: BulkUpdateRecurringPlanSessionsDTO,
  ) {
    return this.recurringPlanService.bulkUpdateFutureSessions(user, id, dto);
  }

  @Patch(':id/sessions/:sessionId')
  @UseGuards(RolesGuard)
  @Roles(UserRole.admin, UserRole.coach)
  @ApiOperation({
    summary:
      'Reschedule or skip one session without changing the parent recurrence template.',
  })
  @ApiParam({ name: 'id', format: 'uuid' })
  @ApiParam({ name: 'sessionId', format: 'uuid' })
  updateSingleSession(
    @CurrentUser() user: JwtPayload,
    @Param('id', ParseUUIDPipe) id: string,
    @Param('sessionId', ParseUUIDPipe) sessionId: string,
    @Body() dto: UpdateRecurringPlanSessionDTO,
  ) {
    return this.recurringPlanService.updateSingleSession(
      user,
      id,
      sessionId,
      dto,
    );
  }

  @Patch(':id/cancel')
  @UseGuards(RolesGuard)
  @Roles(UserRole.admin, UserRole.coach)
  @ApiOperation({
    summary:
      'Cancel a recurring coaching plan and future non-completed sessions only.',
  })
  @ApiParam({ name: 'id', format: 'uuid' })
  cancelPlan(
    @CurrentUser() user: JwtPayload,
    @Param('id', ParseUUIDPipe) id: string,
    @Body() dto: CancelRecurringCoachingPlanDTO,
  ) {
    return this.recurringPlanService.cancelPlan(user, id, dto);
  }
}
