import {
  HttpCode,
  Body,
  Controller,
  Get,
  Headers,
  Param,
  ParseUUIDPipe,
  Patch,
  Post,
  Query,
  UseGuards,
} from '@nestjs/common';
import {
  ApiBearerAuth,
  ApiExtraModels,
  ApiHeader,
  ApiOperation,
  ApiResponse,
  ApiTags,
  getSchemaPath,
} from '@nestjs/swagger';
import { UserRole } from '@prisma/client';

import type { JwtPayload } from '../../auth/types/jwt-payload.type';
import { CurrentUser, Roles } from '../../common/decorators';
import { JwtAuthGuard, RolesGuard } from '../../common/guards';
import {
  CancelSubscriptionDTO,
  CreateSubscriptionDTO,
  CreatePlanDTO,
  CurrentSubscriptionResponseDTO,
  MembershipPlanResponseDTO,
  PaginationDTO,
  SubscriptionCheckoutResponseDTO,
  UpdatePlanDTO,
} from './dto/subscription.dto';
import { SubscriptionService } from './subscription.service';

const paginationMetaSchema = {
  type: 'object',
  properties: {
    page: { type: 'number', example: 1 },
    limit: { type: 'number', example: 20 },
    total: { type: 'number', example: 1 },
    total_pages: { type: 'number', example: 1 },
  },
  required: ['page', 'limit', 'total', 'total_pages'],
};

function apiEnvelopeSchema(schemaRef: string) {
  return {
    type: 'object',
    properties: {
      data: { $ref: schemaRef },
    },
    required: ['data'],
  };
}

function paginatedEnvelopeSchema(itemSchemaRef: string) {
  return {
    type: 'object',
    properties: {
      data: {
        type: 'array',
        items: { $ref: itemSchemaRef },
      },
      meta: paginationMetaSchema,
    },
    required: ['data', 'meta'],
  };
}

@ApiTags('Membership')
@ApiExtraModels(
  MembershipPlanResponseDTO,
  CurrentSubscriptionResponseDTO,
  SubscriptionCheckoutResponseDTO,
)
@Controller('membership')
export class SubscriptionController {
  constructor(private readonly subscriptionService: SubscriptionService) {}

  @Get('plans')
  @ApiOperation({ summary: 'List active membership plans.' })
  @ApiResponse({
    status: 200,
    description: 'Membership plans returned.',
    schema: paginatedEnvelopeSchema(getSchemaPath(MembershipPlanResponseDTO)),
  })
  listPlans(@Query() dto: PaginationDTO) {
    return this.subscriptionService.listPlans(dto);
  }

  @Get('plans/:id')
  @ApiOperation({ summary: 'Get a single active membership plan.' })
  @ApiResponse({
    status: 200,
    description: 'Membership plan returned.',
    schema: apiEnvelopeSchema(getSchemaPath(MembershipPlanResponseDTO)),
  })
  @ApiResponse({ status: 404, description: 'Membership plan not found.' })
  getPlanById(@Param('id', ParseUUIDPipe) id: string) {
    return this.subscriptionService.getPlanById(id);
  }

  @Get('my-subscription')
  @UseGuards(JwtAuthGuard)
  @ApiBearerAuth('access-token')
  @ApiOperation({
    summary: 'Get the authenticated users current subscription.',
  })
  @ApiResponse({
    status: 200,
    description: 'Current subscription returned, or null when none exists.',
    schema: {
      type: 'object',
      properties: {
        data: {
          anyOf: [
            { $ref: getSchemaPath(CurrentSubscriptionResponseDTO) },
            { type: 'null' },
          ],
        },
      },
      required: ['data'],
    },
  })
  getMySubscription(@CurrentUser() user: JwtPayload) {
    return this.subscriptionService.getMySubscription(user.sub);
  }

  @Post('cancel')
  @HttpCode(200)
  @UseGuards(JwtAuthGuard)
  @ApiBearerAuth('access-token')
  @ApiOperation({
    summary: 'Cancel the authenticated users current subscription.',
  })
  @ApiResponse({ status: 200, description: 'Subscription cancelled.' })
  cancelSubscription(
    @CurrentUser() user: JwtPayload,
    @Body() dto: CancelSubscriptionDTO,
  ) {
    return this.subscriptionService.cancelSubscription(user.sub, dto);
  }

  @Post('subscribe')
  @UseGuards(JwtAuthGuard)
  @ApiBearerAuth('access-token')
  @ApiHeader({
    name: 'Idempotency-Key',
    required: true,
    description: 'UUID v4 generated by the client and reused on retries.',
  })
  @ApiOperation({
    summary: 'Create a pending subscription and start PayMongo checkout.',
  })
  @ApiResponse({
    status: 201,
    description: 'Checkout session created or resumed.',
    type: SubscriptionCheckoutResponseDTO,
  })
  @ApiResponse({
    status: 409,
    description: 'Member already has an active or pending subscription.',
  })
  subscribe(
    @CurrentUser() user: JwtPayload,
    @Body() dto: CreateSubscriptionDTO,
    @Headers('idempotency-key') idempotencyKey: string | undefined,
  ) {
    return this.subscriptionService.subscribe(user.sub, dto, idempotencyKey);
  }

  @Post('plans')
  @UseGuards(JwtAuthGuard, RolesGuard)
  @Roles(UserRole.admin, UserRole.staff)
  @ApiBearerAuth('access-token')
  @ApiOperation({ summary: 'Create a membership plan. Admin/Staff only.' })
  @ApiResponse({ status: 201, description: 'Membership plan created.' })
  createPlan(@Body() dto: CreatePlanDTO) {
    return this.subscriptionService.createPlan(dto);
  }

  @Patch('plans/:id')
  @UseGuards(JwtAuthGuard, RolesGuard)
  @Roles(UserRole.admin, UserRole.staff)
  @ApiBearerAuth('access-token')
  @ApiOperation({ summary: 'Update a membership plan. Admin/Staff only.' })
  @ApiResponse({ status: 200, description: 'Membership plan updated.' })
  @ApiResponse({ status: 404, description: 'Membership plan not found.' })
  updatePlan(
    @Param('id', ParseUUIDPipe) id: string,
    @Body() dto: UpdatePlanDTO,
  ) {
    return this.subscriptionService.updatePlan(id, dto);
  }
}
