export const OTP_EXPIRY_MINUTES = 5;
export const OTP_MAX_ATTEMPTS = 3;
export const OTP_LOCK_MINUTES = 15;
export const OTP_HASH_ROUNDS = 12;

export const REGISTRATION_CHALLENGE_TTL_SECONDS = 5 * 60;
export const REGISTRATION_CHALLENGE_MAX_ATTEMPTS = 5;
export const REGISTRATION_CHALLENGE_LOCK_SECONDS = 10 * 60;
export const REGISTRATION_CHALLENGE_PROCESSING_SECONDS = 30;
export const REGISTRATION_CHALLENGE_COMPLETED_TTL_SECONDS = 10 * 60;
