import {
  Body,
  Controller,
  Get,
  Headers,
  Param,
  ParseUUIDPipe,
  Post,
  Query,
  UseGuards,
} from '@nestjs/common';
import {
  ApiBearerAuth,
  ApiBody,
  ApiExtraModels,
  ApiHeader,
  ApiOperation,
  ApiResponse,
  ApiTags,
  getSchemaPath,
} from '@nestjs/swagger';
import { UserRole } from '@prisma/client';

import type { JwtPayload } from '../../auth/types/jwt-payload.type';
import { CurrentUser } from '../../common/decorators/current-user.decorator';
import { Roles } from '../../common/decorators/roles.decorator';
import { JwtAuthGuard } from '../../common/guards/jwt-auth.guard';
import { RolesGuard } from '../../common/guards/roles.guard';
import {
  CreateSaleDTO,
  SaleCheckoutResponseDTO,
  SaleFilterDTO,
  SaleTransactionDetailResponseDTO,
  SaleTransactionSummaryResponseDTO,
} from './dto/sales.dto';
import { SalesService } from './sales.service';

function apiEnvelopeSchema(ref: string) {
  return {
    type: 'object',
    properties: {
      data: { $ref: ref },
    },
  };
}

function paginatedEnvelopeSchema(ref: string) {
  return {
    type: 'object',
    properties: {
      data: {
        type: 'array',
        items: { $ref: ref },
      },
      meta: {
        type: 'object',
        properties: {
          page: { type: 'number', example: 1 },
          limit: { type: 'number', example: 20 },
          total: { type: 'number', example: 1 },
          total_pages: { type: 'number', example: 1 },
        },
      },
    },
  };
}

@ApiTags('Inventory')
@ApiExtraModels(
  SaleTransactionSummaryResponseDTO,
  SaleTransactionDetailResponseDTO,
  SaleCheckoutResponseDTO,
)
@Controller('inventory')
export class SalesController {
  constructor(private readonly salesService: SalesService) {}

  @Post('sales')
  @UseGuards(JwtAuthGuard, RolesGuard)
  @Roles(UserRole.staff)
  @ApiBearerAuth('access-token')
  @ApiHeader({
    name: 'Idempotency-Key',
    required: true,
    description:
      'UUID v4 generated by the client and reused on PayMongo sale retries.',
  })
  @ApiBody({ type: CreateSaleDTO })
  @ApiOperation({
    summary:
      'Create a cash sale or start a PayMongo product checkout. Staff only.',
  })
  @ApiResponse({
    status: 201,
    description: 'Sale transaction created or checkout resumed.',
    schema: {
      oneOf: [
        apiEnvelopeSchema(getSchemaPath(SaleTransactionDetailResponseDTO)),
        apiEnvelopeSchema(getSchemaPath(SaleCheckoutResponseDTO)),
      ],
    },
  })
  @ApiResponse({ status: 404, description: 'A retail product was not found.' })
  @ApiResponse({ status: 422, description: 'Sale input is invalid.' })
  createSale(
    @CurrentUser() user: JwtPayload,
    @Body() dto: CreateSaleDTO,
    @Headers('idempotency-key') idempotencyKey: string | undefined,
  ) {
    return this.salesService.createSale(user.sub, dto, idempotencyKey);
  }

  @Get('sales')
  @UseGuards(JwtAuthGuard, RolesGuard)
  @Roles(UserRole.admin, UserRole.staff)
  @ApiBearerAuth('access-token')
  @ApiOperation({ summary: 'List sale transactions. Admin and staff only.' })
  @ApiResponse({
    status: 200,
    description: 'Sale transactions returned.',
    schema: paginatedEnvelopeSchema(
      getSchemaPath(SaleTransactionSummaryResponseDTO),
    ),
  })
  listSales(@Query() dto: SaleFilterDTO) {
    return this.salesService.listSales(dto);
  }

  @Get('sales/:id')
  @UseGuards(JwtAuthGuard, RolesGuard)
  @Roles(UserRole.admin, UserRole.staff)
  @ApiBearerAuth('access-token')
  @ApiOperation({
    summary:
      'Get a sale transaction with item snapshots. Admin and staff only.',
  })
  @ApiResponse({
    status: 200,
    description: 'Sale transaction returned.',
    schema: apiEnvelopeSchema(getSchemaPath(SaleTransactionDetailResponseDTO)),
  })
  @ApiResponse({ status: 404, description: 'Sale transaction not found.' })
  getSaleById(@Param('id', ParseUUIDPipe) id: string) {
    return this.salesService.getSaleById(id);
  }
}
