import { StyleSheet } from "react-native";

import type { ThemeColors } from "@fittrack/types";
import { MAX_WIDTH, R } from "@fittrack/ui/tokens";

export function makeAppointmentModalStyles(colors: ThemeColors) {
  return StyleSheet.create({
    fill: {
      flex: 1,
    },
    backdrop: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      paddingHorizontal: 20,
    },
    card: {
      width: "100%",
      maxWidth: MAX_WIDTH,
      height: "86%",
      maxHeight: "86%",
      borderRadius: R.xl,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      overflow: "hidden",
    },
    middle: {
      flex: 1,
      minHeight: 0,
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      paddingHorizontal: 16,
      paddingVertical: 14,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    headerIcon: {
      width: 38,
      height: 38,
      borderRadius: R.md,
      borderWidth: 1,
      borderColor: colors.brand + "44",
      backgroundColor: colors.brand + "22",
      alignItems: "center",
      justifyContent: "center",
    },
    headerTitle: {
      fontSize: 16,
      fontWeight: "700",
      color: colors.textPrimary,
    },
    headerSubtitle: {
      fontSize: 12,
      marginTop: 1,
      color: colors.textMuted,
    },
    body: {
      flexGrow: 1,
      paddingHorizontal: 16,
      paddingTop: 14,
      paddingBottom: 24,
      gap: 12,
    },
    sectionLabel: {
      fontSize: 11,
      fontWeight: "700",
      letterSpacing: 0.7,
      color: colors.textMuted,
      marginBottom: 8,
    },
    coachList: {
      gap: 8,
    },
    coachPicker: {
      minWidth: 0,
      gap: 8,
    },
    coachSearchRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      minWidth: 0,
    },
    coachSearch: {
      flex: 1,
      minWidth: 0,
    },
    filterPanel: {
      gap: 8,
      marginBottom: 10,
    },
    filterHeaderRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    filterToggle: {
      width: 44,
      height: 44,
      flexShrink: 0,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: R.md,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surfaceRaised,
    },
    filterBadge: {
      position: "absolute",
      right: 3,
      top: 3,
      minWidth: 16,
      height: 16,
      paddingHorizontal: 3,
      borderRadius: 8,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.brand,
    },
    filterBadgeText: {
      fontSize: 10,
      lineHeight: 13,
      fontWeight: "700",
      color: colors.onBrand,
    },
    filterChipRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 6,
    },
    durationChipRow: {
      rowGap: 10,
      paddingVertical: 5,
    },
    filterChip: {
      borderRadius: R.md,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surfaceRaised,
      minHeight: 44,
      alignItems: "center",
      paddingHorizontal: 10,
      paddingVertical: 8,
    },
    filterChipText: {
      fontSize: 11,
      fontWeight: "600",
      color: colors.textSecondary,
    },
    coachState: {
      minWidth: 0,
      gap: 8,
      paddingVertical: 8,
    },
    durationChip: {
      minHeight: 34,
      justifyContent: "center",
      paddingHorizontal: 10,
      paddingVertical: 8,
    },
    coachCard: {
      minWidth: 0,
      overflow: "hidden",
      borderRadius: R.lg,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surfaceRaised,
    },
    selectedCoachCaption: {
      paddingHorizontal: 12,
      paddingTop: 10,
      color: colors.brand,
      fontSize: 11,
      fontWeight: "700",
      letterSpacing: 0.4,
      textTransform: "uppercase",
    },
    coachRow: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: 12,
      minWidth: 0,
      padding: 12,
    },
    coachAvatar: {
      width: 40,
      height: 40,
      borderRadius: 20,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.brand + "22",
    },
    coachAvatarText: {
      fontSize: 14,
      fontWeight: "700",
      color: colors.brand,
    },
    coachInfo: {
      flex: 1,
      minWidth: 0,
      gap: 4,
    },
    coachNameRow: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: 8,
      minWidth: 0,
    },
    coachName: {
      flex: 1,
      minWidth: 0,
      flexShrink: 1,
      fontSize: 14,
      fontWeight: "600",
      color: colors.textPrimary,
    },
    coachSpecialty: {
      fontSize: 12,
      color: colors.textMuted,
    },
    coachRating: {
      fontSize: 12,
      fontWeight: "700",
      color: colors.warning,
    },
    coachChevron: {
      width: 24,
      minHeight: 44,
      alignItems: "center",
      justifyContent: "center",
      flexShrink: 0,
    },
    coachDetails: {
      minWidth: 0,
      gap: 10,
      paddingHorizontal: 12,
      paddingTop: 10,
      paddingBottom: 12,
      borderTopWidth: 1,
      borderTopColor: colors.border,
    },
    coachDetailsSection: {
      minWidth: 0,
      gap: 6,
    },
    coachDetailsSectionTitle: {
      color: colors.textMuted,
      fontSize: 11,
      fontWeight: "700",
      letterSpacing: 0.7,
    },
    coachDetailsText: {
      color: colors.textSecondary,
      fontSize: 12,
      lineHeight: 18,
    },
    coachBio: {
      fontSize: 12,
      lineHeight: 18,
      color: colors.textMuted,
    },
    coachReviewQuote: {
      fontSize: 12,
      lineHeight: 18,
      color: colors.textSecondary,
      borderLeftWidth: 2,
      borderLeftColor: colors.warning + "88",
      paddingLeft: 8,
    },
    coachMetaRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 6,
      marginTop: 2,
    },
    coachMetaChip: {
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: R.md,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
    },
    coachMetaChipText: {
      fontSize: 11,
      color: colors.textSecondary,
    },
    previewCard: {
      borderRadius: R.lg,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surfaceRaised,
      padding: 14,
      gap: 10,
    },
    previewTitle: {
      fontSize: 14,
      fontWeight: "700",
      color: colors.textPrimary,
    },
    previewSubtitle: {
      fontSize: 12,
      color: colors.textMuted,
      lineHeight: 18,
    },
    previewSection: {
      gap: 6,
    },
    previewSectionTitle: {
      fontSize: 11,
      fontWeight: "700",
      letterSpacing: 0.7,
      color: colors.textMuted,
    },
    previewPlainText: {
      fontSize: 12,
      color: colors.textSecondary,
      lineHeight: 18,
    },
    previewList: {
      gap: 6,
    },
    previewListItem: {
      fontSize: 12,
      color: colors.textSecondary,
      lineHeight: 18,
    },
    planOptionList: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
    },
    planOptionCard: {
      flex: 1,
      minWidth: 132,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: R.md,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      minHeight: 44,
      paddingHorizontal: 12,
      paddingVertical: 10,
    },
    planOptionTitle: {
      fontSize: 13,
      fontWeight: "700",
      color: colors.textPrimary,
    },
    fieldBtn: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      paddingHorizontal: 14,
      paddingVertical: 13,
      borderRadius: R.md,
      borderWidth: 1,
      borderColor: colors.fieldBorder,
      backgroundColor: colors.fieldBg,
      marginBottom: 10,
    },
    fieldBtnText: {
      fontSize: 14,
      flex: 1,
      color: colors.textMuted,
    },
    helperText: {
      fontSize: 12,
      color: colors.textMuted,
      lineHeight: 18,
    },
    paymentHeaderRow: {
      flexDirection: "row",
      alignItems: "flex-start",
      justifyContent: "space-between",
      gap: 10,
    },
    paymentOptionList: {
      gap: 10,
    },
    paymentOptionCard: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: 10,
      borderRadius: R.md,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      padding: 12,
    },
    paymentOptionCardDisabled: {
      opacity: 0.5,
    },
    paymentOptionTitle: {
      fontSize: 14,
      fontWeight: "700",
      color: colors.textPrimary,
    },
    paymentOptionTitleDisabled: {
      color: colors.textMuted,
    },
    paymentOptionBody: {
      fontSize: 12,
      lineHeight: 18,
      color: colors.textMuted,
    },
    paymentOptionBodyDisabled: {
      color: colors.textMuted,
    },
    paymentSummaryCard: {
      borderRadius: R.md,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      padding: 12,
      gap: 8,
    },
    paymentBreakdownRow: {
      flexDirection: "row",
      gap: 10,
      flexWrap: "wrap",
      marginTop: 2,
    },
    paymentBreakdownColumn: {
      flex: 1,
      minWidth: 92,
      gap: 4,
    },
    paymentBreakdownValue: {
      fontSize: 14,
      fontWeight: "700",
      color: colors.textPrimary,
    },
    errorText: {
      fontSize: 12,
      marginTop: 6,
      color: colors.danger,
    },
    footer: {
      flexDirection: "row",
      gap: 10,
      padding: 16,
      borderTopWidth: 1,
      borderTopColor: colors.border,
    },
  });
}
