import { StyleSheet } from "react-native";

import type { ThemeColors } from "@fittrack/types";
import { MAX_WIDTH, R } from "@fittrack/ui/tokens";

export function makeBookingPickerStyles(colors: ThemeColors) {
  return StyleSheet.create({
    backdrop: {
      alignItems: "center",
      flex: 1,
      justifyContent: "center",
      paddingHorizontal: 16,
    },
    card: {
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderRadius: R.xl,
      borderWidth: 1,
      maxHeight: "82%",
      maxWidth: MAX_WIDTH,
      overflow: "hidden",
      width: "100%",
    },
    header: {
      alignItems: "center",
      borderBottomColor: colors.border,
      borderBottomWidth: 1,
      flexDirection: "row",
      gap: 10,
      paddingHorizontal: 16,
      paddingVertical: 14,
    },
    headerIcon: {
      alignItems: "center",
      backgroundColor: colors.brand + "18",
      borderColor: colors.brand + "44",
      borderRadius: R.md,
      borderWidth: 1,
      height: 38,
      justifyContent: "center",
      width: 38,
    },
    headerText: { flex: 1, minWidth: 0 },
    title: { color: colors.textPrimary, fontSize: 16, fontWeight: "700" },
    subtitle: { color: colors.textMuted, fontSize: 12, marginTop: 2 },
    body: { gap: 10, paddingHorizontal: 16, paddingVertical: 14 },
    filters: { flexDirection: "row", flexWrap: "wrap", gap: 7 },
    filterChip: {
      backgroundColor: colors.surfaceRaised,
      borderColor: colors.border,
      borderRadius: R.xl,
      borderWidth: 1,
      paddingHorizontal: 10,
      paddingVertical: 7,
    },
    filterChipText: { color: colors.textSecondary, fontSize: 11, fontWeight: "600" },
    listHost: { flexGrow: 0, maxHeight: 430, minHeight: 0 },
    list: { gap: 8, paddingBottom: 4 },
    row: {
      backgroundColor: colors.surfaceRaised,
      borderColor: colors.border,
      borderRadius: R.md,
      borderWidth: 1,
      flexDirection: "row",
      gap: 10,
      minWidth: 0,
      padding: 12,
    },
    rowBody: { flex: 1, minWidth: 0 },
    rowTitle: { color: colors.textPrimary, fontSize: 14, fontWeight: "700" },
    rowSubtitle: { color: colors.textSecondary, fontSize: 12, marginTop: 3 },
    rowDetail: { color: colors.textMuted, fontSize: 11, marginTop: 3 },
    stateBox: {
      alignItems: "flex-start",
      borderColor: colors.border,
      borderRadius: R.md,
      borderStyle: "dashed",
      borderWidth: 1,
      gap: 8,
      padding: 14,
    },
    stateText: { color: colors.textMuted, fontSize: 12, lineHeight: 18 },
    footer: {
      borderTopColor: colors.border,
      borderTopWidth: 1,
      paddingHorizontal: 16,
      paddingVertical: 12,
    },
  });
}
