import {
  Body,
  Controller,
  Get,
  Headers,
  Param,
  ParseUUIDPipe,
  Patch,
  Post,
  Query,
  UseGuards,
} from '@nestjs/common';
import {
  ApiBearerAuth,
  ApiHeader,
  ApiOperation,
  ApiResponse,
  ApiTags,
} from '@nestjs/swagger';
import { UserRole } from '@prisma/client';

import type { JwtPayload } from '../../auth/types/jwt-payload.type';
import { CurrentUser } from '../../common/decorators/current-user.decorator';
import { Roles } from '../../common/decorators/roles.decorator';
import { JwtAuthGuard } from '../../common/guards/jwt-auth.guard';
import { RolesGuard } from '../../common/guards/roles.guard';
import { DateRangeDTO } from '../../user/dto/user-dto';
import { BookingService } from './booking.service';
import {
  AvailabilityQueryDTO,
  AvailabilitySlotDTO,
} from './dto/availability.dto';
import {
  BookingCheckoutResponseDTO,
  CreateBookingDTO,
  ProcessBalanceDTO,
} from './dto/create-booking.dto';

@ApiTags('Bookings')
@Controller('bookings')
export class BookingController {
  constructor(private readonly bookingService: BookingService) {}

  @Get('amenities/availability')
  @UseGuards(JwtAuthGuard)
  @ApiBearerAuth('access-token')
  @ApiOperation({ summary: 'Get hourly amenity availability for a date.' })
  @ApiResponse({
    status: 200,
    description: 'Availability returned.',
    type: AvailabilitySlotDTO,
    isArray: true,
  })
  @ApiResponse({ status: 400, description: 'Invalid availability query.' })
  @ApiResponse({ status: 404, description: 'Amenity not found.' })
  getAvailability(@Query() dto: AvailabilityQueryDTO) {
    return this.bookingService.getAvailability(dto);
  }

  @Post('amenity')
  @UseGuards(JwtAuthGuard)
  @ApiBearerAuth('access-token')
  @ApiHeader({
    name: 'Idempotency-Key',
    required: true,
    description: 'UUID v4 generated by the client and reused on retries.',
  })
  @ApiOperation({
    summary: 'Create a booking and start or resume full PayMongo checkout.',
  })
  @ApiResponse({
    status: 201,
    description: 'Booking created or checkout resumed.',
    type: BookingCheckoutResponseDTO,
  })
  @ApiResponse({
    status: 409,
    description: 'Booking slot is no longer available.',
  })
  createBooking(
    @CurrentUser() user: JwtPayload,
    @Body() dto: CreateBookingDTO,
    @Headers('idempotency-key') idempotencyKey: string | undefined,
  ) {
    return this.bookingService.createBooking(
      user.sub,
      dto,
      idempotencyKey,
      user.role,
    );
  }

  @Get('amenity/my')
  @UseGuards(JwtAuthGuard)
  @ApiBearerAuth('access-token')
  @ApiOperation({ summary: 'Get the authenticated members booking history.' })
  getMyBookings(@CurrentUser() user: JwtPayload, @Query() dto: DateRangeDTO) {
    return this.bookingService.getMyBookings(user.sub, dto);
  }

  @Get('amenity')
  @UseGuards(JwtAuthGuard, RolesGuard)
  @Roles(UserRole.admin, UserRole.staff)
  @ApiBearerAuth('access-token')
  @ApiOperation({ summary: 'Get all bookings. Admin/Staff only.' })
  getAllBookings(@Query() dto: DateRangeDTO) {
    return this.bookingService.getAllBookings(dto);
  }

  @Patch('amenity/:id/cancel')
  @UseGuards(JwtAuthGuard)
  @ApiBearerAuth('access-token')
  @ApiOperation({
    summary: 'Cancel a pending or confirmed booking.',
  })
  @ApiResponse({ status: 200, description: 'Booking cancelled.' })
  async cancelBooking(
    @Param('id', ParseUUIDPipe) id: string,
    @CurrentUser() user: JwtPayload,
  ) {
    await this.bookingService.cancelBooking(id, user.sub);
    return { message: 'Booking cancelled.' };
  }

  @Post('amenity/:id/balance')
  @UseGuards(JwtAuthGuard, RolesGuard)
  @Roles(UserRole.admin, UserRole.staff)
  @ApiBearerAuth('access-token')
  @ApiOperation({
    summary: 'Start or resume balance collection for a confirmed booking.',
  })
  @ApiResponse({
    status: 201,
    description: 'Balance payment created or resumed.',
    type: BookingCheckoutResponseDTO,
  })
  processBalance(
    @Param('id', ParseUUIDPipe) id: string,
    @Body() dto: ProcessBalanceDTO,
  ) {
    return this.bookingService.processBalance(id, dto);
  }
}
