import { Body, Controller, Headers, Post, UseGuards } from '@nestjs/common';
import {
  ApiBearerAuth,
  ApiExtraModels,
  ApiHeader,
  ApiOperation,
  ApiResponse,
  ApiTags,
} from '@nestjs/swagger';

import type { JwtPayload } from '../../auth/types/jwt-payload.type';
import { CurrentUser } from '../../common/decorators';
import { JwtAuthGuard } from '../../common/guards';
import {
  MembershipCardPurchaseResponseDTO,
  StartMembershipCardPurchaseDTO,
} from './dto/card.dto';
import { MembershipCardService } from './card.service';

@ApiTags('Membership')
@ApiExtraModels(MembershipCardPurchaseResponseDTO)
@UseGuards(JwtAuthGuard)
@ApiBearerAuth('access-token')
@Controller('membership/card')
export class MembershipCardController {
  constructor(private readonly membershipCardService: MembershipCardService) {}

  @Post('purchase')
  @ApiHeader({
    name: 'Idempotency-Key',
    required: true,
    description: 'UUID v4 generated by the client and reused on retries.',
  })
  @ApiOperation({
    summary: 'Start a membership-card purchase through PayMongo checkout.',
  })
  @ApiResponse({
    status: 201,
    description: 'Membership-card purchase started or resumed.',
    type: MembershipCardPurchaseResponseDTO,
  })
  @ApiResponse({
    status: 410,
    description:
      'Member cash membership-card requests are retired; use the authorized admin/staff grant flow.',
  })
  purchase(
    @CurrentUser() user: JwtPayload,
    @Body() dto: StartMembershipCardPurchaseDTO,
    @Headers('idempotency-key') idempotencyKey: string | undefined,
  ) {
    return this.membershipCardService.purchase(user.sub, dto, idempotencyKey);
  }
}
