import {
  Body,
  Controller,
  Get,
  Headers,
  Param,
  ParseUUIDPipe,
  Patch,
  Post,
  Query,
  UseGuards,
} from '@nestjs/common';
import {
  ApiBearerAuth,
  ApiExtraModels,
  ApiHeader,
  ApiOperation,
  ApiResponse,
  ApiTags,
  getSchemaPath,
} from '@nestjs/swagger';
import { UserRole } from '@prisma/client';

import type { JwtPayload } from '../../auth/types/jwt-payload.type';
import { CurrentUser } from '../../common/decorators/current-user.decorator';
import { Roles } from '../../common/decorators/roles.decorator';
import { JwtAuthGuard } from '../../common/guards/jwt-auth.guard';
import { RolesGuard } from '../../common/guards/roles.guard';
import { DateRangeDTO } from '../../user/dto/user-dto';
import { AppointmentService } from './appointment.service';
import { CoachingCheckoutResponseDTO } from '../commerce/dto/coaching-commerce.dto';
import {
  AppointmentBalanceDTO,
  AppointmentCheckoutResponseDTO,
  AppointmentResponseDTO,
  CancelAppointmentDTO,
  ChangeAppointmentStatusDTO,
  CoachAvailabilityQueryDTO,
  CoachAvailabilitySlotResponseDTO,
  CoachScheduleAppointmentResponseDTO,
  CompleteAppointmentDTO,
  CreateCoachManagedAppointmentDTO,
  CreateAppointmentDTO,
  InitiateAppointmentPaymentDTO,
  RespondAppointmentDTO,
  RescheduleAppointmentDTO,
  SetAvailabilityDTO,
  SubmitCoachFeedbackDTO,
} from './dto/appointment.dto';

function apiEnvelopeSchema(ref: string) {
  return {
    type: 'object',
    properties: {
      data: { $ref: ref },
    },
    required: ['data'],
  };
}

function nullableEnvelopeSchema() {
  return {
    type: 'object',
    properties: {
      data: {
        type: 'null',
        nullable: true,
        example: null,
      },
    },
    required: ['data'],
  };
}

function messageEnvelopeSchema(message: string) {
  return {
    type: 'object',
    properties: {
      data: {
        type: 'object',
        properties: {
          message: { type: 'string', example: message },
        },
        required: ['message'],
      },
    },
    required: ['data'],
  };
}

function paginatedEnvelopeSchema(itemSchemaRef: string) {
  return {
    type: 'object',
    properties: {
      data: {
        type: 'array',
        items: { $ref: itemSchemaRef },
      },
      meta: {
        type: 'object',
        properties: {
          page: { type: 'number', example: 1 },
          limit: { type: 'number', example: 20 },
          total: { type: 'number', example: 1 },
          total_pages: { type: 'number', example: 1 },
        },
      },
    },
    required: ['data', 'meta'],
  };
}

@ApiTags('Coaching')
@ApiExtraModels(
  AppointmentResponseDTO,
  AppointmentCheckoutResponseDTO,
  CoachingCheckoutResponseDTO,
  CoachScheduleAppointmentResponseDTO,
)
@Controller('coaching')
export class AppointmentController {
  constructor(private readonly appointmentService: AppointmentService) {}

  @Post('coaches/availability')
  @UseGuards(JwtAuthGuard, RolesGuard)
  @Roles(UserRole.coach)
  @ApiBearerAuth('access-token')
  @ApiOperation({
    summary: 'Replace the authenticated coach weekly availability.',
  })
  @ApiResponse({
    status: 200,
    description: 'Availability updated.',
    schema: nullableEnvelopeSchema(),
  })
  async setAvailability(
    @CurrentUser() user: JwtPayload,
    @Body() dto: SetAvailabilityDTO,
  ) {
    await this.appointmentService.setAvailability(user.sub, dto);
    return null;
  }

  @Get('coaches/:coachId/availability')
  @UseGuards(JwtAuthGuard)
  @ApiBearerAuth('access-token')
  @ApiOperation({
    summary:
      'Get canonical coach availability excluding confirmed appointments and live checkout holds.',
  })
  @ApiResponse({
    status: 200,
    description: 'Canonical coach availability returned.',
    type: CoachAvailabilitySlotResponseDTO,
    isArray: true,
  })
  getCoachAvailability(
    @Param('coachId', ParseUUIDPipe) coachId: string,
    @Query() dto: CoachAvailabilityQueryDTO,
  ) {
    return this.appointmentService.getAvailability(coachId, dto);
  }

  @Post('appointments')
  @UseGuards(JwtAuthGuard)
  @ApiBearerAuth('access-token')
  @ApiHeader({
    name: 'Idempotency-Key',
    required: true,
    description: 'UUID v4 generated by the client and reused on retries.',
  })
  @ApiOperation({
    summary:
      'Create an internal full-PayMongo checkout hold; the appointment is created only after a successful webhook.',
  })
  @ApiResponse({
    status: 201,
    description: 'Checkout hold created or resumed.',
    schema: apiEnvelopeSchema(getSchemaPath(CoachingCheckoutResponseDTO)),
  })
  createAppointment(
    @CurrentUser() user: JwtPayload,
    @Headers('idempotency-key') idempotencyKey: string | undefined,
    @Body() dto: CreateAppointmentDTO,
  ) {
    return this.appointmentService.createAppointment(
      user.sub,
      dto,
      idempotencyKey,
    );
  }

  @Post('appointments/coach-managed')
  @UseGuards(JwtAuthGuard, RolesGuard)
  @Roles(UserRole.coach)
  @ApiBearerAuth('access-token')
  @ApiOperation({
    summary:
      'Create a confirmed client appointment from the authenticated coach dashboard.',
  })
  @ApiResponse({
    status: 201,
    description: 'Coach-managed appointment created.',
    schema: apiEnvelopeSchema(getSchemaPath(AppointmentResponseDTO)),
  })
  createCoachManagedAppointment(
    @CurrentUser() user: JwtPayload,
    @Body() dto: CreateCoachManagedAppointmentDTO,
  ) {
    return this.appointmentService.createCoachManagedAppointment(user.sub, dto);
  }

  @Patch('appointments/:id/reschedule')
  @UseGuards(JwtAuthGuard, RolesGuard)
  @Roles(UserRole.admin, UserRole.staff, UserRole.coach)
  @ApiBearerAuth('access-token')
  @ApiHeader({
    name: 'Idempotency-Key',
    required: true,
    description:
      'UUID v4 generated by the client and reused with the same payload on retries.',
  })
  @ApiOperation({
    summary:
      'Reschedule one existing paid, confirmed one-time coaching appointment; this changes this session only.',
  })
  @ApiResponse({
    status: 200,
    description:
      'The exact appointment was updated without creating a booking, payment, or recurring-plan change.',
    schema: apiEnvelopeSchema(getSchemaPath(AppointmentResponseDTO)),
  })
  @ApiResponse({ status: 403, description: 'Requester is not authorized.' })
  @ApiResponse({ status: 409, description: 'Appointment or coach slot is not eligible.' })
  rescheduleAppointment(
    @Param('id', ParseUUIDPipe) id: string,
    @CurrentUser() user: JwtPayload,
    @Headers('idempotency-key') idempotencyKey: string | undefined,
    @Body() dto: RescheduleAppointmentDTO,
  ) {
    return this.appointmentService.rescheduleAppointment(
      user.sub,
      user.role,
      id,
      dto,
      idempotencyKey,
    );
  }

  @Get('appointments/my')
  @UseGuards(JwtAuthGuard)
  @ApiBearerAuth('access-token')
  @ApiOperation({
    summary: 'Get the authenticated members appointment history.',
  })
  @ApiResponse({
    status: 200,
    description: 'Appointments returned.',
    schema: paginatedEnvelopeSchema(getSchemaPath(AppointmentResponseDTO)),
  })
  getMyAppointments(
    @CurrentUser() user: JwtPayload,
    @Query() dto: DateRangeDTO,
  ) {
    return this.appointmentService.getMyAppointments(user.sub, dto);
  }

  @Get('appointments/coach')
  @UseGuards(JwtAuthGuard, RolesGuard)
  @Roles(UserRole.coach)
  @ApiBearerAuth('access-token')
  @ApiOperation({
    summary: 'Get the authenticated coach appointment schedule.',
  })
  @ApiResponse({
    status: 200,
    description: 'Coach schedule returned.',
    schema: paginatedEnvelopeSchema(
      getSchemaPath(CoachScheduleAppointmentResponseDTO),
    ),
  })
  getCoachAppointments(
    @CurrentUser() user: JwtPayload,
    @Query() dto: DateRangeDTO,
  ) {
    return this.appointmentService.getCoachAppointments(user.sub, dto);
  }

  @Patch('appointments/:id/respond')
  @UseGuards(JwtAuthGuard, RolesGuard)
  @Roles(UserRole.coach)
  @ApiBearerAuth('access-token')
  @ApiOperation({
    summary:
      'Accept or reject a legacy pending-coach appointment request as the coach.',
  })
  @ApiResponse({
    status: 200,
    description: 'Legacy appointment response recorded.',
    schema: apiEnvelopeSchema(getSchemaPath(AppointmentResponseDTO)),
  })
  respondToAppointment(
    @Param('id', ParseUUIDPipe) id: string,
    @CurrentUser() user: JwtPayload,
    @Body() dto: RespondAppointmentDTO,
  ) {
    return this.appointmentService.respondToAppointment(user.sub, id, dto);
  }

  @Patch('appointments/:id/cancel')
  @UseGuards(JwtAuthGuard)
  @ApiBearerAuth('access-token')
  @ApiOperation({
    summary: 'Cancel an appointment subject to the applicable payment policy.',
  })
  @ApiResponse({
    status: 200,
    description: 'Appointment cancelled.',
    schema: messageEnvelopeSchema(
      'Appointment cancelled. Payment handling follows the applicable payment policy.',
    ),
  })
  async cancelAppointment(
    @Param('id', ParseUUIDPipe) id: string,
    @CurrentUser() user: JwtPayload,
    @Body() dto: CancelAppointmentDTO,
  ) {
    await this.appointmentService.cancelAppointment(
      user.sub,
      user.role,
      id,
      dto,
    );
    return {
      message:
        'Appointment cancelled. Payment handling follows the applicable payment policy.',
    };
  }

  @Patch('appointments/:id/status')
  @UseGuards(JwtAuthGuard, RolesGuard)
  @Roles(UserRole.admin, UserRole.staff, UserRole.coach)
  @ApiBearerAuth('access-token')
  @ApiOperation({
    summary:
      'Change a coaching appointment status without date-window restrictions.',
  })
  @ApiResponse({
    status: 200,
    description: 'Appointment status changed.',
    schema: apiEnvelopeSchema(getSchemaPath(AppointmentResponseDTO)),
  })
  changeAppointmentStatus(
    @Param('id', ParseUUIDPipe) id: string,
    @CurrentUser() user: JwtPayload,
    @Body() dto: ChangeAppointmentStatusDTO,
  ) {
    return this.appointmentService.changeAppointmentStatus(
      user.sub,
      user.role,
      id,
      dto,
    );
  }

  @Post('appointments/:id/pay')
  @UseGuards(JwtAuthGuard)
  @ApiBearerAuth('access-token')
  @ApiHeader({
    name: 'Idempotency-Key',
    required: true,
    description: 'UUID v4 generated by the client and reused on retries.',
  })
  /** @deprecated Retained only as a 410 full-payment compatibility route. */
  @ApiOperation({
    summary: 'Deprecated appointment payment compatibility route.',
  })
  @ApiResponse({ status: 410, description: 'Payment route retired.' })
  initiateDownpayment(
    @Param('id', ParseUUIDPipe) id: string,
    @CurrentUser() user: JwtPayload,
    @Headers('idempotency-key') idempotencyKey: string | undefined,
    @Body() dto: InitiateAppointmentPaymentDTO,
  ) {
    return this.appointmentService.initiateDownpayment(
      user.sub,
      user.role,
      id,
      dto,
      idempotencyKey,
    );
  }

  @Post('appointments/:id/balance')
  @UseGuards(JwtAuthGuard, RolesGuard)
  @Roles(UserRole.admin, UserRole.staff)
  @ApiBearerAuth('access-token')
  /** @deprecated Retained only as a 410 full-payment compatibility route. */
  @ApiOperation({
    summary: 'Deprecated appointment balance collection route.',
  })
  @ApiResponse({ status: 410, description: 'Balance route retired.' })
  processBalance(
    @Param('id', ParseUUIDPipe) id: string,
    @CurrentUser() user: JwtPayload,
    @Body() dto: AppointmentBalanceDTO,
  ) {
    return this.appointmentService.processBalance(user.sub, id, dto);
  }

  @Patch('appointments/:id/complete')
  @UseGuards(JwtAuthGuard, RolesGuard)
  @Roles(UserRole.coach)
  @ApiBearerAuth('access-token')
  @ApiOperation({
    summary:
      'Mark a confirmed coaching appointment complete with a session report.',
  })
  @ApiResponse({
    status: 200,
    description: 'Appointment marked complete.',
    schema: apiEnvelopeSchema(getSchemaPath(AppointmentResponseDTO)),
  })
  completeAppointment(
    @Param('id', ParseUUIDPipe) id: string,
    @CurrentUser() user: JwtPayload,
    @Body() dto: CompleteAppointmentDTO,
  ) {
    return this.appointmentService.completeAppointment(user.sub, id, dto);
  }

  @Patch('appointments/:id/feedback')
  @UseGuards(JwtAuthGuard, RolesGuard)
  @Roles(UserRole.coach)
  @ApiBearerAuth('access-token')
  @ApiOperation({
    summary: 'Submit coach feedback and an optional assessment report.',
  })
  @ApiResponse({
    status: 200,
    description: 'Coach feedback saved.',
    schema: apiEnvelopeSchema(getSchemaPath(AppointmentResponseDTO)),
  })
  submitCoachFeedback(
    @Param('id', ParseUUIDPipe) id: string,
    @CurrentUser() user: JwtPayload,
    @Body() dto: SubmitCoachFeedbackDTO,
  ) {
    return this.appointmentService.submitCoachFeedback(user.sub, id, dto);
  }
}
